### ISSUE TITLE
reset all button migrates to latest notebook cell.

### ISSUE THREAD

**Issue by tawheeler** [tawheeler/CrossfilterCharts.jl#11]
If you run multiple DC visualizations in a single notebook, the reset_all button will move to the latest cell. See the doc notebook for an example.

**Comment by session-id** [comment]
This seems to be a big overall issue with the new iframe-less output: since the outputs are no longer separated by the iframe barrier, they can actually interfere with each other. Most notably, attempting to output the same dcout twice will cause the second to display nothing (since all the supposedly unique chart_id's are bound to the objects in the first chart output).

**Comment by session-id** [comment]
I've decided to randomize the id's given to each chart every time the output is produced to avoid the above problem. Still working on the reset buttons.
